export function getData() {
  const rowData = [
    {
      ID: '1',
      Category: 'Interior / Exterior',
      InspectionLine: 'Bulbs and Lights',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '2',
      Category: 'Interior / Exterior',
      InspectionLine:
        'Windshield Wipers / Windshield Washer Spray / Wiper Operation / Wiper Blades Wiper Arms /',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '3',
      Category: 'Interior / Exterior',
      InspectionLine: 'Including Rear (if applicable)',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '4',
      Category: 'Interior / Exterior',
      InspectionLine:
        'Windshield Condition (inspect for Cracks, Chips, or Pitting)',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '5',
      Category: 'Interior / Exterior',
      InspectionLine: 'Upholstery / Carpet / Floor Mats / Mirrors / Glass',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '6',
      Category: 'Interior / Exterior',
      InspectionLine: 'Emergency Brake Adjustment',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '7',
      Category: 'Interior / Exterior',
      InspectionLine: 'Horn Operation *',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '8',
      Category: 'Interior / Exterior',
      InspectionLine: 'Fuel Tank Cap Gasket *',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '9',
      Category: 'Interior / Exterior',
      InspectionLine: 'Clutch Operation (if equipped)',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '10',
      Category: 'Interior / Exterior',
      InspectionLine: 'Air Conditioning Filter (if equipped) *',
      LastServiceDate: '1/20/18',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '11',
      Category: 'Interior / Exterior',
      InspectionLine: 'Cabin/HEPA Filter (if equipped) *',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '12',
      Category: 'Interior / Exterior',
      InspectionLine: 'Engine Air Filter *',
      LastServiceDate: '8/9/20',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '13',
      Category: 'Interior / Exterior',
      InspectionLine: 'Wiper Blades',
      LastServiceDate: '8/10/20',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '14',
      Category: 'Under the hood',
      InspectionLine: 'Engine Oil',
      LastServiceDate: '5/23/22',
      PreviousInspection: 'Passed',
      LastServiceMileage: '33,890',
    },
    {
      ID: '15',
      Category: 'Under the hood',
      InspectionLine: 'Engine Air Filter *',
      LastServiceDate: '5/23/22',
      PreviousInspection: 'Passed',
      LastServiceMileage: '33,890',
    },
    {
      ID: '16',
      Category: 'Under the hood',
      InspectionLine: 'Drive Belts (condition and adjustment)',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '17',
      Category: 'Under the hood',
      InspectionLine: 'Engine Coolant *',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '18',
      Category: 'Driver side front',
      InspectionLine: 'PSI Before',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '19',
      Category: 'Driver side front',
      InspectionLine: 'PSI Set to',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '20',
      Category: 'Driver side front',
      InspectionLine: 'Tread depth 32nds',
      LastServiceDate: '10/10/21',
      PreviousInspection: 'Passed',
      LastServiceMileage: '12,789',
      Condition: '10 32nds',
    },
    {
      ID: '21',
      Category: 'Driver side front',
      InspectionLine: 'Wear pattern/damage',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '22',
      Category: 'Passenger side front',
      InspectionLine: 'PSI Before',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '23',
      Category: 'Passenger side front',
      InspectionLine: 'PSI Set to',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '24',
      Category: 'Passenger side front',
      InspectionLine: 'Tread depth 32nds',
      LastServiceDate: '10/10/21',
      PreviousInspection: 'Risk',
      LastServiceMileage: '12,789',
      Condition: '8 32nds',
    },
    {
      ID: '25',
      Category: 'Passenger side front',
      InspectionLine: 'Wear pattern/damage',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '26',
      Category: 'Driver side rear',
      InspectionLine: 'PSI Before',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '27',
      Category: 'Driver side rear',
      InspectionLine: 'PSI Set to',
      PreviousInspection: 'Passed',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '28',
      Category: 'Driver side rear',
      InspectionLine: 'Tread depth 32nds',
      LastServiceDate: '10/10/21',
      PreviousInspection: 'Passed',
      LastServiceMileage: '12,789',
      Condition: '11 32nds',
    },
    {
      ID: '29',
      Category: 'Driver side rear',
      InspectionLine: 'Wear pattern/damage',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '30',
      Category: 'Passenger side rear',
      InspectionLine: 'PSI Before',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '31',
      Category: 'Passenger side rear',
      InspectionLine: 'PSI Set to',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '32',
      Category: 'Passenger side rear',
      InspectionLine: 'Tread depth 32nds',
      LastServiceDate: '10/10/21',
      PreviousInspection: 'Passed',
      LastServiceMileage: '12,789',
      Condition: '10 32nds',
    },
    {
      ID: '33',
      Category: 'Passenger side rear',
      InspectionLine: 'Wear pattern/damage',
      LastServiceDate: '',
      PreviousInspection: 'Passed',
      LastServiceMileage: '',
      Condition: '',
    },
    {
      ID: '34',
      Category: 'Front breaks',
      InspectionLine: '(mm) Driver front',
      LastServiceDate: '1/19/22',
      PreviousInspection: 'Failed ',
      LastServiceMileage: '25,789',
      Condition: '3 mm',
      Service: 'Replaced',
    },
    {
      ID: '35',
      Category: 'Front breaks',
      InspectionLine: '(mm) Passenger front',
      LastServiceDate: '1/19/22',
      PreviousInspection: 'Failed ',
      LastServiceMileage: '25,789',
      Condition: '2 mm',
      Service: 'Replaced',
    },
    {
      ID: '36',
      Category: 'Rear breaks',
      InspectionLine: '(mm) Driver rear',
      LastServiceDate: '1/19/22',
      PreviousInspection: 'Failed ',
      LastServiceMileage: '25,789',
      Condition: '2 mm',
      Service: 'Replaced',
    },
    {
      ID: '37',
      Category: 'Rear breaks',
      InspectionLine: '(mm) Passenger rear',
      LastServiceDate: '1/19/22',
      PreviousInspection: 'Failed ',
      LastServiceMileage: '25,789',
      Condition: '2 mm',
      Service: 'Replaced',
    },
  ];
  return rowData;
}
